stages:
   - build
   - deploy

build-job:
  stage: build
  before_script:
    - cp {$ENV} .env
    - cp {$ENV_TEST} .env-test
  script:
    - docker build -t expenses-api-image .

deploy-job:
  stage: deploy
  script:
    - docker compose up -d
