stages:
  - build
  - lint_format
  - migrations
  - tests
  - deploy

build-job:
  stage: build
  before_script:
    - cp ${ENV} .env
    - cp ${ENV_TEST} .env-test
  script:
    - docker build -t expenses-api-image .

Lint:
  stage: lint_format
  script:
    - docker run --rm --network myNetwork expenses-api-image ruff check

Format:
  stage: lint_format
  script:
    - docker run --rm --network myNetwork expenses-api-image ruff format --check

Migrations job:
  stage: migrations
  script: docker run --rm --network myNetwork expenses-api-image alembic upgrade head

tests job:
  stage: tests
  script: docker run --rm --network myNetwork expenses-api-image pytest -s -v

deploy-job:
  stage: deploy
  script:
    - docker compose -f docker-compose-ci.yml up -d
    - docker exec expenses_nginx nginx -s reload
