services:
  expenses_back_service:
    container_name: 'expenses_back'
    build:
      context: .
#    ports:
#      - '7777:8000'
    volumes:
      - .:/app
    networks:
      - myNetwork
    env_file:
      - .env

networks:
  myNetwork:
    external: true