# ruff: noqa

"""add column visible into Category

Revision ID: bc8864f11564
Revises: 9e7636533640
Create Date: 2026-01-11 19:02:22.545705

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bc8864f11564"
down_revision: Union[str, Sequence[str], None] = "9e7636533640"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "categories",
        sa.Column(
            "visible", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("categories", "visible")
    # ### end Alembic commands ###
